[package]
name = "awander"
version = "0.1.0"
authors = ["Talia-12 <paradox.m.burgess@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
csv = "1.3.0"
ratatui = "0.24.0"
serde = { version = "1.0.193", features = ["derive"] }
